apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss-capstone
  labels:
    app: ss-capstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ss-capstone
  template:
    metadata:
      labels:
        app: ss-capstone
    spec:
      containers:
      - name: sswebserver
        image: stellasalyga/sswebserver:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  selector:
    app: ss-capstone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080