version: 2.1

        
jobs:
  envbuild:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/capstonev1
    steps:
      - checkout
# Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
  # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install

            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
# run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
  prep-image-docker:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
         name: Build and Upload Docker Image
         command: |
          chmod +x run_docker.sh
          bash run_docker.sh
  deploy-image-docker:
    docker:
      - image: cimg/base:2022.06
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build and push to Docker Hub
          command: |
            docker build -t $DOCKER_USER/$IMAGE_NAME:latest .
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $DOCKER_USER/$IMAGE_NAME:latest


workflows:
  default:
    jobs:
      - envbuild
      - prep-image-docker:
          requires:
            - envbuild    
      - deploy-image-docker:
          requires:
            - prep-image-docker        
